#nlp.run
model nlp.mod;

data dataGeneration/data/blacklabel_rimes.dat;
data dataGeneration/data/blacklabel_enchainement.dat;
data dataGeneration/data/blacklabel_syllabes.dat;
data dataGeneration/data/blacklabel_index.dat;
data dataGeneration/data/blacklabel_n.dat;

option solver cplex;
option cplex_options "mipdisplay=2";
solve;

for {b in L} {
	for{i in N} {
		if m1[b, i] = 1 then {
			printf " %s", index[i];
		}
	}
}

printf "\n";

for {b in L} {
	for{i in N} {
		if m2[b, i] = 1 then {
			printf " %s", index[i];
		}
	}
}
printf "\n";
