#nlp.run
model nlp.mod;

data dataGeneration/data/blacklabel_rimes.dat;
data dataGeneration/data/blacklabel_enchainement.dat;
data dataGeneration/data/blacklabel_syllabes.dat;
data dataGeneration/data/blacklabel_index.dat;

option solver ilogcp;
option ilogcp_options "logverbosity=terse";
solve;
for {i in L} {
  printf " %s", word[x1[i]];
}
printf "\n";

for {i in L} {
  printf " %s", word[x2[i]];
}
printf "\n";

