#nlp.run
model nlp.mod;

data dataGeneration/data/hugo_short_rimes.dat;
data dataGeneration/data/hugo_short_enchainement.dat;
data dataGeneration/data/hugo_short_syllabes.dat;
data dataGeneration/data/hugo_short_index.dat;
data dataGeneration/data/hugo_short_n.dat;

option solver ilogcp;
option ilogcp_options "logverbosity=terse timelimit=500";
solve;

for {b in L} {
	for{i in N} {
		if i > 0 then {
			if m1[b, i] = 1 then {
				printf " %s", index[i];
			}
		}
	}
}

printf "\n";

for {b in L} {
	for{i in N} {
		if i > 0 then {
			if m2[b, i] = 1 then {
				printf " %s", index[i];
			}
		}
	}
}
printf "\n";
